### PR TITLE
Added FeelsAmazingMan

### PR DESCRIPTION
**Pull request by voloshink**
FeelsAmazingMan

### CODE REVIEW

**Comment by PinkishCow** [comment]
Why tho?  I'm this is a pretty shite addition when in my opinion the only thing that needs to be done is emotes being removed.  If BryceMatthes thinks it's decent though do whatever.  Sorry if shits fucked I'm on mobile atm

**Comment by downthecrop** [comment]
FeelsAmazingMan is a fun emote to add imo. We'll be cleaning up garbage like HerbPerv, GabeN, and TopCake but my reasoning for okaying this is that I already put in FeelsGoodMan and FeelsBadMan.

I think we'll poll to check if chat is happy with removing some other ones too (I remember talking about this a while back).

Pretty sure this is going to be the last edition to emotes for a while though. After NotLikeThis we're sitting pretty happy until a fresh meme comes around.

**Comment by PinkishCow** [comment]
Sure thing.  Sounds decent

**Comment by voloshink** [comment]
Added due to requests from TS people to amend for my sins

**Comment by PurpleCox** [comment]
No problem lad,  just my opinions  aslong as the eternal master is fine with it I am

**Pull request merged**
